# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enrico Galassi
description: >- # this means to ignore newlines until "baseurl:"
  A blog on .NET technologies, software design, development and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://galassie.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Enrico Galassi
  icon: me-icon.png
  email: enrico.galassi.88@gmail.com
  github: https://github.com/galassie
  linkedin: https://www.linkedin.com/in/enricogalassi

post-social-share:
  twitter:
    enable: true
    icon: twitter-icon.png
  facebook:
    enable: true
    icon: facebook-icon.png
  googleplus:
    enable: true
    icon: googleplus-icon.png
  linkedin:
    enable: true
    icon: linkedin-icon.png

github: [metadata]
repository: galassie/galassie.github.io

excerpt_length: 50

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sidebar_home_link:  true

disqus:
  shortname: enricogalassi

paginate: 5
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plugins:
  - jekyll-feed
  - jekyll-sitemap